version: 1.0.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_wap: true
  verbosity: minimal
##notifications:
##- provider: Slack
##  incoming_webhook: ##Hook URL for Slack Integration
##  channel: ##Channel Name
##  on_build_success: true
##  on_build_failure: true
##  on_build_status_changed: false